# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://smarttask_ai:smarttask%40123@newcluster.u52lqkm.mongodb.net/smarttask?retryWrites=true&w=majority&appName=newcluster
spring.data.mongodb.database=smarttask

# App name
spring.application.name=backend


# JWT
jwt.secret=smarttask2026supersecretkey1234567890abcdefghij
jwt.expiration=86400000